export const PROVINSI_INDONESIA: string[] = [
  'Aceh',
  'Sumatera Utara',
  'Sumatera Barat',
  'Riau',
  'Kepulauan Riau',
  'Jambi',
  'Sumatera Selatan',
  'Bangka Belitung',
  'Bengkulu',
  'Lampung',
  'DKI Jakarta',
  'Jawa Barat',
  'Banten',
  'Jawa Tengah',
  'DI Yogyakarta',
  'Jawa Timur',
  'Bali',
  'Nusa Tenggara Barat',
  'Nusa Tenggara Timur',
  'Kalimantan Barat',
  'Kalimantan Tengah',
  'Kalimantan Selatan',
  'Kalimantan Timur',
  'Kalimantan Utara',
  'Sulawesi Utara',
  'Gorontalo',
  'Sulawesi Tengah',
  'Sulawesi Barat',
  'Sulawesi Selatan',
  'Sulawesi Tenggara',
  'Maluku',
  'Maluku Utara',
  'Papua',
  'Papua Barat',
  'Papua Selatan',
  'Papua Tengah',
  'Papua Pegunungan',
  'Papua Barat Daya',
];

export const KABUPATEN_KOTA_MAP: { [provinsi: string]: string[] } = {
  'Jawa Timur': ['Kota Surabaya', 'Kota Malang', 'Kab. Sidoarjo', 'Kab. Gresik', 'Kota Kediri', 'Kab. Malang', 'Kab. Pasuruan', 'Kota Pasuruan', 'Kab. Jember', 'Kab. Banyuwangi', 'Kota Madiun', 'Kab. Mojokerto', 'Kota Mojokerto', 'Kab. Tuban', 'Kab. Lamongan', 'Kab. Blitar'],
  'Jawa Tengah': ['Kota Semarang', 'Kota Surakarta (Solo)', 'Kota Magelang', 'Kab. Banyumas (Purwokerto)', 'Kab. Kudus', 'Kab. Pati', 'Kab. Pekalongan', 'Kota Pekalongan', 'Kab. Jepara', 'Kab. Boyolali', 'Kab. Sukoharjo', 'Kab. Cilacap', 'Kab. Brebes', 'Kab. Tegal'],
  'DI Yogyakarta': ['Kota Yogyakarta', 'Kab. Sleman', 'Kab. Bantul', 'Kab. Kulon Progo', 'Kab. Gunungkidul'],
  'Jawa Barat': ['Kota Bandung', 'Kota Bekasi', 'Kota Depok', 'Kota Bogor', 'Kab. Bandung', 'Kab. Bogor', 'Kab. Bekasi', 'Kota Cimahi', 'Kota Cirebon', 'Kab. Cirebon', 'Kota Tasikmalaya', 'Kab. Karawang', 'Kab. Sukabumi', 'Kab. Cianjur', 'Kab. Sumedang'],
  'DKI Jakarta': ['Jakarta Selatan', 'Jakarta Pusat', 'Jakarta Barat', 'Jakarta Timur', 'Jakarta Utara', 'Kepulauan Seribu'],
  'Banten': ['Kota Tangerang', 'Kota Tangerang Selatan', 'Kota Serang', 'Kota Cilegon', 'Kab. Tangerang', 'Kab. Serang', 'Kab. Lebak', 'Kab. Pandeglang'],
  'Bali': ['Kota Denpasar', 'Kab. Badung', 'Kab. Gianyar', 'Kab. Buleleng', 'Kab. Tabanan', 'Kab. Karangasem', 'Kab. Jembrana'],
  'Sumatera Utara': ['Kota Medan', 'Kab. Deli Serdang', 'Kota Pematangsiantar', 'Kota Binjai', 'Kab. Simalungun', 'Kota Tebing Tinggi'],
  'Sumatera Selatan': ['Kota Palembang', 'Kota Prabumulih', 'Kab. Ogan Komering Ilir', 'Kab. Muara Enim'],
  'Kalimantan Timur': ['Kota Samarinda', 'Kota Balikpapan', 'Kota Bontang', 'Kab. Kutai Kartanegara'],
  'Sulawesi Selatan': ['Kota Makassar', 'Kab. Gowa', 'Kota Parepare', 'Kab. Maros', 'Kab. Bone'],
};

export const getKabupatenList = (provinsi: string): string[] => {
  return KABUPATEN_KOTA_MAP[provinsi] || [];
};
